
services:
  solar_prediction:
    build: .
    container_name: solar_prediction_service
    ports:
      - "2802:8099"
    volumes:
      - ./app:/opt/app
      - ./instance:/data/instance
      - ./options.json:/data/options.json
    # entrypoint: ./run.sh
    restart: always
    working_dir: /opt/app